import React,{useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,Text,TextInput,View} from 'react-native';
import {useRouter} from 'expo-router';
import {getPremiumDiscoveries} from '../lib/api';
import {getMe,hasToken,requestCode,verifyCode} from '../lib/api';
import {AppShell,BarChart,Card,LockedCard,Pill,ScoreRing,SectionHeader,s} from '../components/ui';
import {useFeatureAccess} from '../lib/features';
import {C} from '../lib/theme';

export default function BlueOcean(){const router=useRouter(); const access=useFeatureAccess('blue_ocean');const [loading,setLoading]=useState(true);const [allowed,setAllowed]=useState(false);const [email,setEmail]=useState('');const [code,setCode]=useState('');const [sent,setSent]=useState(false);const [msg,setMsg]=useState('');const [discoveries,setDiscoveries]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);
 useEffect(()=>{(async()=>{try{if(await hasToken()){const me=await getMe();setAllowed(!!me.isSubscriber)}}catch{}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!access.loading&&access.feature?.enabled&&(access.feature?.subscriberOnly?allowed:true)){getPremiumDiscoveries('blue_ocean').then(r=>{const rows=r.discoveries||[];setDiscoveries(rows);setSelected(rows[0]||null)}).catch(e=>setMsg(e.message))}},[access.loading,access.feature?.enabled,access.feature?.subscriberOnly,allowed]);
 const top=useMemo(()=>discoveries.slice(0,6),[discoveries]);
 if(!access.loading && (!access.feature || !access.feature.enabled))return <AppShell active="blue-ocean" title="Blue Ocean" subtitle="Feature currently unavailable"><Card><SectionHeader title="Temporarily unavailable" subtitle="See Stats has disabled this feature from the backend admin console."/></Card></AppShell>;
 const send=async()=>{setMsg('');try{await requestCode(email.trim().toLowerCase());setSent(true);setMsg('Code sent. Check your email. The subscriber access session lasts 3 days.')}catch(e:any){setMsg(e.message)}};
 const verify=async()=>{setMsg('');try{const me=await verifyCode(email.trim().toLowerCase(),code.trim());setAllowed(!!me.isSubscriber);if(!me.isSubscriber)setMsg('Your email is verified, but it is not currently marked as an active subscriber.')}catch(e:any){setMsg(e.message)}};
 if(loading||access.loading)return <AppShell active="blue-ocean" title="Blue Ocean" subtitle="Subscriber intelligence"><ActivityIndicator color={C.accent}/></AppShell>;
 if(access.feature?.subscriberOnly && !allowed)return <AppShell active="blue-ocean" title="Blue Ocean" subtitle="Subscriber intelligence"><LockedCard onPress={()=>{}}/><Card><SectionHeader title="Unlock Blue Ocean" subtitle="This area is reserved for subscribers. Request a short-lived access code sent to your subscriber email."/><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@company.com" placeholderTextColor={C.muted} style={s.searchInput as any}/>{sent&&<TextInput value={code} onChangeText={setCode} placeholder="6-digit code" placeholderTextColor={C.muted} keyboardType="number-pad" style={[s.searchInput as any,{marginTop:10,backgroundColor:C.panel2,padding:12,borderRadius:10}]}/>}<View style={{flexDirection:'row',gap:8,marginTop:12}}>{!sent?<Pressable onPress={send} style={{backgroundColor:C.accent,paddingHorizontal:16,paddingVertical:11,borderRadius:11}}><Text style={{fontWeight:'900',color:'#07111f'}}>Email me a code</Text></Pressable>:<Pressable onPress={verify} style={{backgroundColor:C.accent,paddingHorizontal:16,paddingVertical:11,borderRadius:11}}><Text style={{fontWeight:'900',color:'#07111f'}}>Unlock for 3 days</Text></Pressable>}</View>{msg&&<Text style={{color:msg.toLowerCase().includes('sent')?C.accent:C.gold,fontSize:12,marginTop:12,lineHeight:18}}>{msg}</Text>}</Card><Card><Text style={{color:C.text,fontWeight:'800'}}>What subscribers see</Text><Text style={{color:C.muted,fontSize:12,lineHeight:18,marginTop:7}}>Undiscovered export products, first-mover scores, market-entry playbooks, demand signals, target buyer archetypes, risks and 90-day launch actions.</Text></Card></AppShell>;
 if(!selected)return <AppShell active="blue-ocean" title="Blue Ocean" subtitle="Private discovery engine"><ActivityIndicator color={C.accent}/><Text style={{color:C.muted,fontSize:12,marginTop:8}}>{msg||'Loading the latest discovery set…'}</Text></AppShell>;
 return <AppShell active="blue-ocean" title="Blue Ocean" subtitle="Private discovery engine · subscriber access active"><Card><SectionHeader title="Ghana's next categories" subtitle="Ranked by saturation, local advantage, demand trajectory, entry barriers and first-mover potential"/><BarChart data={top.map(d=>({label:d.name.split('(')[0].trim().slice(0,16),value:d.total_score}))}/></Card><View style={{flexDirection:'row',gap:14,flexWrap:'wrap'}}><View style={{flex:1,minWidth:300,gap:8}}>{top.map(d=><Pressable key={d.id} onPress={()=>setSelected(d)} style={{backgroundColor:selected.id===d.id?C.panel2:C.panel,borderRadius:14,borderWidth:1,borderColor:selected.id===d.id?C.accent:C.line,padding:14}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><ScoreRing score={d.total_score} size={58}/><View style={{flex:1}}><Text style={{color:C.text,fontWeight:'800'}}>{d.name.split('(')[0].trim()}</Text><Text style={{color:C.muted,fontSize:11,marginTop:3}}>{d.blue_ocean_tier} · {d.gross_margin_pct}% gross margin</Text></View></View></Pressable>)}</View><Card style={{flex:1,minWidth:300}}><Pill tone="good">{selected.blue_ocean_tier}</Pill><Text style={{color:C.text,fontSize:22,fontWeight:'900',marginTop:10}}>{selected.name}</Text><Text style={{color:C.muted,fontSize:12,lineHeight:19,marginTop:8}}>{selected.why_undiscovered}</Text><SectionHeader title="Why now" subtitle={`${selected.global_market_size_usd} · ${selected.demand_cagr_pct}% demand CAGR`}/><View style={{gap:8,marginTop:10}}>{selected.first_mover_actions.slice(0,5).map((x,i)=><Text key={x} style={{color:C.muted,fontSize:11,lineHeight:17}}><Text style={{color:C.accent,fontWeight:'800'}}>{i+1}. </Text>{x}</Text>)}</View><Text style={{color:C.text,fontWeight:'800',marginTop:18}}>Key risks</Text>{selected.risks.slice(0,3).map(x=><Text key={x} style={{color:C.muted,fontSize:11,lineHeight:17,marginTop:5}}>• {x}</Text>)}</Card></View></AppShell>}
