import React,{useEffect,useMemo,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {useRouter} from 'expo-router';
import {analysis as seed} from '../lib/data';
import {getCountryReport} from '../lib/api';
import {AppShell,FeatureGate,Card,Pill,ScoreRing,SearchBox,SectionHeader,s} from '../components/ui';
import {C} from '../lib/theme';
export default function Opportunities(){const router=useRouter();const [analysis,setAnalysis]=useState(seed);const [q,setQ]=useState(''); useEffect(()=>{getCountryReport('GHA').then(r=>r.analysis&&setAnalysis(r.analysis)).catch(()=>{});},[]);const [tab,setTab]=useState<'all'|'import'|'export'>('all');const all=[...analysis.import_opportunities,...analysis.export_opportunities];const rows=useMemo(()=>all.filter(o=>(tab==='all'||o.type.startsWith(tab))&&o.commodity.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.score-a.score),[q,tab]);return <FeatureGate featureKey="opportunities"><AppShell active="opportunities" title="Opportunity radar" subtitle="Ranked trade and investment themes for Ghana">
 <View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>{[['all','All'],['import','Import'],['export','Export']].map(([k,l])=><Pressable key={k} onPress={()=>setTab(k as any)} style={{paddingHorizontal:13,paddingVertical:9,borderRadius:20,backgroundColor:tab===k?C.accent:C.panel}}><Text style={{color:tab===k?'#07111f':C.muted,fontWeight:'800',fontSize:11}}>{l}</Text></Pressable>)}<View style={{flex:1,minWidth:220}}><SearchBox value={q} onChange={setQ} placeholder="Find a commodity"/></View></View>
 <Card><SectionHeader title={`${rows.length} ranked opportunities`} subtitle="Tap a row for the economics, supply/demand context and suggested next actions"/><View style={{marginTop:12,gap:8}}>{rows.map((o,i)=><Pressable key={o.commodity} onPress={()=>router.push({pathname:'/opportunity',params:{id:o.commodity}})} style={{padding:13,backgroundColor:C.panel2,borderRadius:13,flexDirection:'row',alignItems:'center',gap:12}}><Text style={{color:C.muted,width:20}}>{i+1}</Text><View style={{flex:1}}><View style={{flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'}}><Text style={{color:C.text,fontWeight:'800'}}>{o.commodity}</Text><Pill tone={o.type==='export_opportunity'?'good':'info'}>{o.type==='export_opportunity'?'EXPORT':'IMPORT'}</Pill></View><Text style={{color:C.muted,fontSize:11,marginTop:5}}>{o.yoy_growth_pct}% YoY · {o.margin_pct}% est. margin · {o.budget_fit?'Budget fit':'Capital intensive'}</Text></View><ScoreRing score={o.score} size={56}/></Pressable>)}</View></Card>
 </AppShell></FeatureGate>}
