import React from 'react';
import {Pressable,Text,View} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {analysis} from '../../lib/data';
import {AppShell,FeatureGate,BarChart,Card,Pill,ScoreRing,SectionHeader} from '../../components/ui';
import {C} from '../../lib/theme';
export default function OpportunityDetail(){const {id}=useLocalSearchParams<{id?:string}>();const router=useRouter();const name=decodeURIComponent(id||'');const o=[...analysis.import_opportunities,...analysis.export_opportunities].find(x=>x.commodity===name)||analysis.top_5_overall[0];const isExport=o.type==='export_opportunity';return <FeatureGate featureKey="opportunities"><AppShell active="opportunities" title={o.commodity} subtitle={`${isExport?'Export':'Import'} opportunity · Ghana`}>
 <View style={{flexDirection:'row',gap:14,alignItems:'center',flexWrap:'wrap'}}><ScoreRing score={o.score} size={92}/><View style={{flex:1,minWidth:240}}><View style={{flexDirection:'row',gap:8}}><Pill tone={isExport?'good':'info'}>{isExport?'EXPORT':'IMPORT'}</Pill><Pill tone={o.margin_flag==='green'?'good':o.margin_flag==='yellow'?'warn':'bad'}>{o.margin_pct}% margin</Pill></View><Text style={{color:C.text,fontSize:26,fontWeight:'900',marginTop:8}}>{o.commodity}</Text><Text style={{color:C.muted,fontSize:12,marginTop:4}}>Growth {o.yoy_growth_pct}% YoY · estimated starting order GHC {o.est_order_ghc.toLocaleString()}</Text></View></View>
 <View style={{flexDirection:'row',gap:14,flexWrap:'wrap'}}>{isExport?<><Metric title="Ghana exports" value={`$${o.ghana_export_usd_m}M`} /><Metric title="Best market" value={o.best_market||'—'} /><Metric title="Market demand" value={`+${o.market_demand_growth_pct}%`} /><Metric title="Producer price" value={`$${o.ghana_producer_price_usd_mt}/MT`} /></>:<><Metric title="Ghana imports" value={`$${o.ghana_import_usd_m}M`} /><Metric title="Best supplier" value={o.best_supplier||'—'} /><Metric title="Source price" value={`$${o.best_price_usd_mt}/MT`} /><Metric title="Order quantity" value={`${o.est_order_qty_mt} MT`} /></>}</View>
 <View style={{flexDirection:'row',gap:16,flexWrap:'wrap'}}><Card style={{flex:1,minWidth:300}}><SectionHeader title="Why the signal is strong" subtitle="Score components from the current model"/><BarChart data={Object.entries(o.score_breakdown).map(([label,value])=>({label:label.replaceAll('_',' '),value:Number(value)}))}/></Card><Card style={{flex:1,minWidth:300}}><SectionHeader title={isExport?'Target markets':'Supply options'}/><View style={{gap:8,marginTop:12}}>{(isExport?o.all_markets:o.all_suppliers)?.map((x:any)=><View key={x.country} style={{padding:12,backgroundColor:C.panel2,borderRadius:12}}><Text style={{color:C.text,fontWeight:'800'}}>{x.country}</Text><Text style={{color:C.muted,fontSize:11,marginTop:3}}>{isExport?`Demand +${x.demand_growth_pct}% · ${x.price_premium} premium`:`$${x.price_usd_mt}/MT · ${x.distance} logistics`}</Text></View>)}</View></Card></View>
 <Card><SectionHeader title="Investor diligence" subtitle="Use the signal to decide what to investigate next, not as an automatic buy recommendation"/><View style={{gap:8,marginTop:12}}>{['Confirm the latest source publication date and methodology','Validate landed cost, taxes, FX, freight and working-capital requirements','Identify 3+ credible counterparties and obtain written quotations','Test a small transaction or buyer commitment before scaling','Record regulatory, quality, sanctions and country-risk constraints'].map((x,i)=><View key={x} style={{flexDirection:'row',gap:10,alignItems:'flex-start'}}><Text style={{color:C.accent,fontWeight:'900'}}>{i+1}</Text><Text style={{color:C.muted,fontSize:12,lineHeight:18,flex:1}}>{x}</Text></View>)}</View></Card>
 <Pressable onPress={()=>router.push('/opportunities')}><Text style={{color:C.accent,fontWeight:'800'}}>← Back to opportunity radar</Text></Pressable>
 </AppShell></FeatureGate>}
function Metric({title,value}:{title:string;value:string}){return <Card style={{flex:1,minWidth:160}}><Text style={{color:C.muted,fontSize:10,textTransform:'uppercase',fontWeight:'800'}}>{title}</Text><Text style={{color:C.text,fontSize:20,fontWeight:'900',marginTop:8}}>{value}</Text></Card>}
