import React,{useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {useRouter} from 'expo-router';
import {AppShell,Card,SectionHeader,s} from '../components/ui';
import {C} from '../lib/theme';
import {requestCode,verifyCode} from '../lib/api';

export default function SubscriberAccess(){
 const router=useRouter(); const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 const send=async()=>{setBusy(true);setMsg('');try{await requestCode(email.trim().toLowerCase());setSent(true);setMsg('Code sent. Check your email. The code expires in 3 days and can be used once.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const verify=async()=>{setBusy(true);setMsg('');try{const me=await verifyCode(email.trim().toLowerCase(),code.trim());if(me.isSubscriber){setMsg('Access activated. You can now open any subscriber feature.');}else setMsg('Your email is not currently active as a subscriber.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 return <AppShell active="account" title="Subscriber access" subtitle="Unlock features your See Stats plan includes"><Card><SectionHeader title="Email verification" subtitle="Enter the email address that your administrator has activated as a subscriber."/><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@company.com" placeholderTextColor={C.muted} style={[s.searchInput as any,{marginTop:14,backgroundColor:C.panel2,padding:12,borderRadius:10}]}/>{sent&&<TextInput value={code} onChangeText={setCode} placeholder="6-digit code" placeholderTextColor={C.muted} keyboardType="number-pad" style={[s.searchInput as any,{marginTop:10,backgroundColor:C.panel2,padding:12,borderRadius:10}]}/>}<View style={{flexDirection:'row',gap:8,marginTop:12}}><Pressable disabled={busy} onPress={sent?verify:send} style={{backgroundColor:C.accent,paddingHorizontal:16,paddingVertical:11,borderRadius:11,opacity:busy?.6:1}}><Text style={{fontWeight:'900',color:'#07111f'}}>{busy?'Working…':sent?'Verify & unlock':'Email me a code'}</Text></Pressable><Pressable onPress={()=>router.back()} style={{backgroundColor:C.panel2,paddingHorizontal:16,paddingVertical:11,borderRadius:11}}><Text style={{fontWeight:'800',color:C.text}}>Back</Text></Pressable></View>{msg&&<Text style={{color:msg.toLowerCase().includes('sent')||msg.toLowerCase().includes('activated')?C.accent:C.gold,fontSize:12,marginTop:12,lineHeight:18}}>{msg}</Text>}</Card><Card><Text style={{color:C.text,fontWeight:'800'}}>How access works</Text><View style={{gap:8,marginTop:9}}>{['Your administrator activates your email as a subscriber.','See Stats emails a one-time 6-digit access code.','The code expires after 3 days.','A successful verification creates a 3-day subscriber session.','Your access follows the features your administrator has marked as subscriber-only.'].map((x,i)=><Text key={x} style={{color:C.muted,fontSize:12,lineHeight:18}}><Text style={{color:C.accent,fontWeight:'800'}}>{i+1}. </Text>{x}</Text>)}</View></Card></AppShell>
}
